# Generated by Django 6.0.4 on 2026-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='soumis_stock',
            field=models.BooleanField(default=False, help_text='Cochez si le produit doit être géré en stock'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Quantité en stock'),
        ),
        migrations.AddField(
            model_name='produit',
            name='temps_preparation_defini',
            field=models.BooleanField(default=False, help_text='Cochez pour définir un temps de préparation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='temps_preparation',
            field=models.PositiveIntegerField(blank=True, help_text='Temps de préparation en minutes', null=True),
        ),
    ]
