# Generated by Django 6.0.7 on 2026-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_produit_soumis_stock_produit_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresselivraison',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
