# Generated by Django 6.0.4 on 2026-08-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_alter_adresselivraison_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='a_livree',
            field=models.BooleanField(default=False, help_text='Cochez si la commande doit être livrée'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_app.adresselivraison'),
        ),
    ]
