# Generated by Django 6.0.4 on 2026-08-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_commande_a_livree_alter_commande_adresse_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='order_app.livreur'),
        ),
    ]
