# Generated by Django 6.0.7 on 2026-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_commande_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='taille',
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, help_text='Générée automatiquement (PROD-xxxxxx)', max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='TailleProduit',
        ),
    ]
