from django.urls import path
from order_app import views

urlpatterns = [
    path('order/list', views.order_list, name='order_list'),
    path('order/create', views.commande_create, name='commande_create'),
    path('order/<int:pk>', views.commande_detail, name='commande_detail'),
    path('order/<int:pk>/edit', views.commande_update, name='commande_update'),
    path('order/<int:pk>/statut', views.commande_statut, name='commande_statut'),
    path('order/<int:pk>/delete', views.commande_delete, name='commande_delete'),
    path('clients/list', views.clients_list, name='clients_list'),
    path('clients/<int:pk>', views.client_detail, name='client_detail'),
    path('clients/create', views.client_create, name='client_create'),
    path('clients/<int:pk>/edit', views.client_update, name='client_update'),
    path('clients/<int:pk>/delete', views.client_delete, name='client_delete'),
    path('products/list', views.products_list, name='products_list'),
    path('products/<int:pk>', views.produit_detail, name='produit_detail'),
    path('products/create', views.produit_create, name='produit_create'),
    path('products/<int:pk>/edit', views.produit_update, name='produit_update'),
    path('products/<int:pk>/delete', views.produit_delete, name='produit_delete'),
    path('products/<int:pk>/stock', views.produit_mouvement_stock, name='produit_stock_mouvement'),
    path('stock/mouvements/list', views.mouvements_stock_list, name='mouvements_stock_list'),
    path('factures/list', views.factures_list, name='factures_list'),
    path('factures/<int:pk>', views.facture_detail, name='facture_detail'),
    path('factures/<int:pk>/delete', views.facture_delete, name='facture_delete'),
    path('factures/<int:pk>/payer', views.facture_paiement, name='facture_paiement'),
    path('paiements/list', views.paiements_list, name='paiements_list'),
    path('paiements/create', views.paiement_create, name='paiement_create'),
    path('paiements/<int:pk>/delete', views.paiement_delete, name='paiement_delete'),
    path('livraisons/list', views.livraisons_list, name='livraisons_list'),
    path('livraisons/<int:pk>/statut', views.livraison_statut, name='livraison_statut'),
    path('livraisons/<int:pk>', views.livraison_detail, name='livraison_detail'),
    path('adresses/livraison', views.adresses_livraison_list, name='adresses_livraison_list'),
    path('adresses/create', views.adresse_create, name='adresse_create'),
    path('adresses/<int:pk>/edit', views.adresse_update, name='adresse_update'),
    path('adresses/<int:pk>/delete', views.adresse_delete, name='adresse_delete'),
    path('categories/list', views.categories_list, name='categories_list'),
    path('categories/create', views.categorie_create, name='categorie_create'),
    path('categories/<int:pk>/edit', views.categorie_update, name='categorie_update'),
    path('categories/<int:pk>/delete', views.categorie_delete, name='categorie_delete'),
    path('livreurs/list', views.livreurs_list, name='livreurs_list'),
    path('livreurs/create', views.livreur_create, name='livreur_create'),
    path('livreurs/<int:pk>/edit', views.livreur_update, name='livreur_update'),
    path('livreurs/<int:pk>/delete', views.livreur_delete, name='livreur_delete'),
]